# Generated by Django 5.1.2 on 2024-10-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=3)),
                ('Nationality', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer_name', models.CharField(max_length=50)),
                ('Employer_Email', models.EmailField(max_length=254)),
                ('Employer_Telephone', models.CharField(max_length=15)),
                ('Contact_person', models.CharField(max_length=25)),
                ('PO_Box', models.CharField(max_length=10000)),
                ('Plot_Number', models.IntegerField()),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jobposting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_Title', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Vacancies_Available', models.IntegerField()),
                ('Posting_Date', models.DateField()),
                ('Application_Deadline', models.DateField()),
            ],
        ),
    ]
