# Generated by Django 5.1.2 on 2024-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='Nationality',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='PO_Box',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='Plot_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
