# Generated by Django 5.1.2 on 2024-11-03 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0002_alter_applicant_gender_alter_applicant_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_date', models.DateField()),
                ('Application_status', models.CharField(max_length=20)),
                ('Applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_app.applicant')),
                ('Position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_app.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='Jobrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_level', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=50)),
                ('Employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_app.employer')),
                ('Position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_app.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification_name', models.CharField(max_length=50)),
                ('Qualification_Acronym', models.CharField(max_length=10)),
                ('Awarding_institution', models.CharField(max_length=50)),
                ('Applicant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment_app.applicant')),
            ],
        ),
    ]
